version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name prod-${CIRCLE_WORKFLOW_ID}

  get_instance_ip:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Get instance IP
          command: |
            echo "[all]" > ~/inventory
            aws ec2 describe-instances \
              --query "Reservations[].Instances[].PublicIpAddress" \
              --output text >> ~/inventory
            yum install -y tar
            yum install -y gzip
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - attach_workspace:
          at: ~/
      - checkout
      - add_ssh_keys:
          fingerprints: ["45:44:e9:b4:35:84:f7:3f:e3:f9:5f:e5:a0:95:2a:b1"]
      - run:
          name: check the inventory file content
          command: |
            cat ~/inventory
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: disbale host key checking
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
      - run:
          name: Configure server
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook -i ~/inventory playbook.yml --force-handlers
      - run: return 1
      - destroy_environment
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
      - get_instance_ip:
          requires:
            - create_infrastructure
      - configure_infrastructure:
          requires:
            - get_instance_ip